version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: fitness_db
      POSTGRES_USER: fitness_user
      POSTGRES_PASSWORD: fitness_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  main-app:
    build: ./src/fit
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://fitness_user:fitness_password@db:5432/fitness_db
      - COACH_SERVICE_URL=http://coach-service:5001
      - USE_COACH_MICROSERVICE=true
    depends_on:
      - db
      - coach-service
    volumes:
      - ./src/fit:/app

  coach-service:
    build: ./src/coach
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production

volumes:
  postgres_data: