version: '3.8'

services:
  monolith:
    build:
      context: ./src/fit
    container_name: monolith
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - USE_COACH_MICROSERVICE=true
      - COACH_SERVICE_URL=http://coach:5001
      - SECRET_KEY=fit-secret-key
    depends_on:
      - coach

  coach:
    build:
      context: ./src/coach
    container_name: coach
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
    deploy:
      replicas: 2